=== au-research/ANDS-ResearchVocabularies-Registry/src/test/resources/deploy/test/dbunit-roles-export-choice.dtd
<!ELEMENT dataset (
   (AUTHENTICATION_BUILT_IN|
    ROLES|
    ROLE_RELATIONS)*)>

<!ELEMENT AUTHENTICATION_BUILT_IN EMPTY>
<!ATTLIST AUTHENTICATION_BUILT_IN
    ID CDATA #IMPLIED
    CREATED_WHEN CDATA #IMPLIED
    CREATED_WHO CDATA #IMPLIED
    MODIFIED_WHEN CDATA #IMPLIED
    MODIFIED_WHO CDATA #IMPLIED
    PASSPHRASE_SHA1 CDATA #IMPLIED
    ROLE_ID CDATA #IMPLIED
>

<!ELEMENT ROLES EMPTY>
<!ATTLIST ROLES
    NAME CDATA #IMPLIED
    REMARKS CDATA #IMPLIED
    ID CDATA #IMPLIED
    ID CDATA #IMPLIED
    AUTHENTICATION_SERVICE_ID CDATA #IMPLIED
    CREATED_WHEN CDATA #IMPLIED
    CREATED_WHO CDATA #IMPLIED
    EMAIL CDATA #IMPLIED
    ENABLED CDATA #IMPLIED
    LAST_LOGIN CDATA #IMPLIED
    MODIFIED_WHEN CDATA #IMPLIED
    MODIFIED_WHO CDATA #IMPLIED
    NAME CDATA #IMPLIED
    OAUTH_ACCESS_TOKEN CDATA #IMPLIED
    OAUTH_DATA CDATA #IMPLIED
    PERSISTENT_ID CDATA #IMPLIED
    ROLE_ID CDATA #IMPLIED
    ROLE_TYPE_ID CDATA #IMPLIED
    SHARED_TOKEN CDATA #IMPLIED
>

<!ELEMENT ROLE_RELATIONS EMPTY>
<!ATTLIST ROLE_RELATIONS
    ID CDATA #IMPLIED
    CHILD_ROLE_ID CDATA #IMPLIED
    CREATED_WHEN CDATA #IMPLIED
    CREATED_WHO CDATA #IMPLIED
    MODIFIED_WHEN CDATA #IMPLIED
    MODIFIED_WHO CDATA #IMPLIED
    PARENT_ROLE_ID CDATA #IMPLIED
>

=== au-research/ANDS-ResearchVocabularies-Registry/src/test/resources/deploy/test/tests/RegistryModelWorkflowTests.testApplyChangesCurrentVoVREVeAPVAW11/input-roles-dbunit.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "../../dbunit-roles-export-choice.dtd" >
<dataset>

  <!-- passphrase=test -->
  <AUTHENTICATION_BUILT_IN ID="1" ROLE_ID="TEST" PASSPHRASE_SHA1="a94a8fe5ccb19ba61c4c0873d391e987982fbbd3" CREATED_WHO="u1" CREATED_WHEN="2014-09-25 14:45:42.0" MODIFIED_WHO="u1"/>
  <AUTHENTICATION_BUILT_IN ID="2" ROLE_ID="test2" PASSPHRASE_SHA1="a94a8fe5ccb19ba61c4c0873d391e987982fbbd3" CREATED_WHO="u1" CREATED_WHEN="2014-09-30 10:00:01.0" MODIFIED_WHO="u1"/>
  <AUTHENTICATION_BUILT_IN ID="3" ROLE_ID="testsuper1" PASSPHRASE_SHA1="a94a8fe5ccb19ba61c4c0873d391e987982fbbd3" CREATED_WHO="u1" CREATED_WHEN="2014-09-30 10:00:01.0" MODIFIED_WHO="u1"/>


  <ROLE_RELATIONS ID="1" PARENT_ROLE_ID="REGISTRY_USER" CHILD_ROLE_ID="REGISTRY_STAFF" CREATED_WHO="SYSTEM" CREATED_WHEN="2013-05-15 10:02:34.0" MODIFIED_WHEN="2013-05-15 10:02:34.0" MODIFIED_WHO="SYSTEM"/>
  <ROLE_RELATIONS ID="2" PARENT_ROLE_ID="REGISTRY_STAFF" CHILD_ROLE_ID="VOCABS_REGISTRY_SUPERUSER" CREATED_WHO="SYSTEM" CREATED_WHEN="2013-05-15 10:02:34.0" MODIFIED_WHEN="2013-05-15 10:02:34.0" MODIFIED_WHO="SYSTEM"/>
  <ROLE_RELATIONS ID="3" PARENT_ROLE_ID="VOCABS_REGISTRY_SUPERUSER" CHILD_ROLE_ID="testsuper1" CREATED_WHO="u1" CREATED_WHEN="2015-11-02 12:32:04.0" MODIFIED_WHO="SYSTEM"/>
  <ROLE_RELATIONS ID="4" PARENT_ROLE_ID="REGISTRY_USER" CHILD_ROLE_ID="TEST" CREATED_WHO="SYSTEM" CREATED_WHEN="2013-05-15 10:02:34.0" MODIFIED_WHEN="2013-05-15 10:02:34.0" MODIFIED_WHO="SYSTEM"/>
  <ROLE_RELATIONS ID="5" PARENT_ROLE_ID="REGISTRY_USER" CHILD_ROLE_ID="test2" CREATED_WHO="SYSTEM" CREATED_WHEN="2013-05-15 10:02:34.0" MODIFIED_WHEN="2013-05-15 10:02:34.0" MODIFIED_WHO="SYSTEM"/>

  <ROLE_RELATIONS ID="6" PARENT_ROLE_ID="ANDS" CHILD_ROLE_ID="TEST" CREATED_WHO="u1" CREATED_WHEN="2017-04-12 10:47:54.0" MODIFIED_WHEN="2017-04-12 10:47:54.0" MODIFIED_WHO="SYSTEM"/>
  <ROLE_RELATIONS ID="7" PARENT_ROLE_ID="Org1" CHILD_ROLE_ID="TEST" CREATED_WHO="u1" CREATED_WHEN="2015-11-02 12:32:04.0" MODIFIED_WHO="SYSTEM"/>
  <ROLE_RELATIONS ID="8" PARENT_ROLE_ID="Org1" CHILD_ROLE_ID="test2" CREATED_WHO="u1" CREATED_WHEN="2015-11-02 12:32:04.0" MODIFIED_WHO="SYSTEM"/>
  <ROLE_RELATIONS ID="9" PARENT_ROLE_ID="ANDS" CHILD_ROLE_ID="testsuper1" CREATED_WHO="u1" CREATED_WHEN="2017-04-12 10:47:54.0" MODIFIED_WHEN="2017-04-12 10:47:54.0" MODIFIED_WHO="SYSTEM"/>
  <ROLE_RELATIONS ID="10" PARENT_ROLE_ID="ANDS-Curated" CHILD_ROLE_ID="TEST" CREATED_WHO="u1" CREATED_WHEN="2017-04-12 10:47:54.0" MODIFIED_WHEN="2017-04-12 10:47:54.0" MODIFIED_WHO="SYSTEM"/>


  <ROLES ID="1" ROLE_ID="PUBLIC" ROLE_TYPE_ID="ROLE_FUNCTIONAL" NAME="Public" AUTHENTICATION_SERVICE_ID="" ENABLED="1" CREATED_WHEN="2014-08-13 10:14:56.0" CREATED_WHO="SYSTEM" MODIFIED_WHO="SYSTEM" MODIFIED_WHEN="2014-09-03 11:19:49.0" LAST_LOGIN="2013-09-12 09:24:26.0"/>
  <ROLES ID="2" ROLE_ID="REGISTRY_USER" ROLE_TYPE_ID="ROLE_FUNCTIONAL" NAME="Registry Data Source Admin" AUTHENTICATION_SERVICE_ID="" ENABLED="1" CREATED_WHEN="2014-08-13 10:14:56.0" CREATED_WHO="SYSTEM" MODIFIED_WHO="SYSTEM" MODIFIED_WHEN="2014-09-03 11:19:50.0" LAST_LOGIN="2013-09-12 09:24:27.0"/>
  <ROLES ID="3" ROLE_ID="REGISTRY_STAFF" ROLE_TYPE_ID="ROLE_FUNCTIONAL" NAME="Registry Staff Member" AUTHENTICATION_SERVICE_ID="" ENABLED="1" CREATED_WHEN="2014-08-13 10:14:56.0" CREATED_WHO="SYSTEM" MODIFIED_WHO="SYSTEM" MODIFIED_WHEN="2014-09-03 11:19:50.0" LAST_LOGIN="2013-09-12 09:24:27.0"/>
  <ROLES ID="4" ROLE_ID="VOCABS_REGISTRY_SUPERUSER" ROLE_TYPE_ID="ROLE_FUNCTIONAL" NAME="Vocabs Registry Superuser" AUTHENTICATION_SERVICE_ID="" ENABLED="1" CREATED_WHEN="2014-08-13 10:14:56.0" CREATED_WHO="SYSTEM" MODIFIED_WHO="SYSTEM" MODIFIED_WHEN="2014-09-03 11:19:50.0" LAST_LOGIN="2013-09-12 09:24:27.0"/>

  <ROLES ID="5" ROLE_ID="Org1" ROLE_TYPE_ID="ROLE_ORGANISATIONAL" NAME="Organization 1" AUTHENTICATION_SERVICE_ID="" ENABLED="1" CREATED_WHEN="2014-08-13 10:14:56.0" CREATED_WHO="Tester" MODIFIED_WHO="Tester" MODIFIED_WHEN="2014-09-03 11:19:49.0" LAST_LOGIN="2013-09-12 09:24:26.0"/>
  <ROLES ID="6" ROLE_ID="Org2" ROLE_TYPE_ID="ROLE_ORGANISATIONAL" NAME="Organization 2" AUTHENTICATION_SERVICE_ID="AUTHENTICATION_BUILT_IN" ENABLED="1" CREATED_WHEN="2014-08-13 10:14:56.0" CREATED_WHO="u1" MODIFIED_WHO="SYSTEM"/>

  <ROLES ID="7" ROLE_ID="TEST" ROLE_TYPE_ID="ROLE_USER" NAME="Test 1" AUTHENTICATION_SERVICE_ID="AUTHENTICATION_BUILT_IN" ENABLED="1" CREATED_WHEN="2014-09-25 14:45:42.0" CREATED_WHO="u1" MODIFIED_WHO="SYSTEM" MODIFIED_WHEN="2014-09-25 14:45:42.0"/>
  <ROLES ID="8" ROLE_ID="test2" ROLE_TYPE_ID="ROLE_USER" NAME="Test 2" AUTHENTICATION_SERVICE_ID="AUTHENTICATION_BUILT_IN" ENABLED="1" CREATED_WHEN="2014-09-30 10:00:13.0" CREATED_WHO="u1" MODIFIED_WHO="SYSTEM" MODIFIED_WHEN="2016-08-01 10:47:35.0" LAST_LOGIN="2016-08-01 10:47:35.0"/>

  <ROLES ID="9" ROLE_ID="testsuper1" ROLE_TYPE_ID="ROLE_USER" NAME="Test Super 1" AUTHENTICATION_SERVICE_ID="AUTHENTICATION_BUILT_IN" ENABLED="1" CREATED_WHEN="2014-09-30 10:00:13.0" CREATED_WHO="u1" MODIFIED_WHO="SYSTEM" MODIFIED_WHEN="2016-08-01 10:47:35.0" LAST_LOGIN="2016-08-01 10:47:35.0"/>

  <ROLES ID="10" ROLE_ID="ANDS" ROLE_TYPE_ID="ROLE_ORGANISATIONAL" NAME="Australian National Data Service" AUTHENTICATION_SERVICE_ID="AUTHENTICATION_BUILT_IN" ENABLED="1" CREATED_WHEN="2014-11-05 10:33:01.0" CREATED_WHO="u1" MODIFIED_WHO="SYSTEM" MODIFIED_WHEN="2014-11-05 10:33:01.0"/>
  <ROLES ID="11" ROLE_ID="ANDS_STAFF" ROLE_TYPE_ID="ROLE_FUNCTIONAL" NAME="ANDS Employees" AUTHENTICATION_SERVICE_ID="AUTHENTICATION_BUILT_IN" ENABLED="1" CREATED_WHEN="2014-11-05 10:37:08.0" CREATED_WHO="u1" MODIFIED_WHO="SYSTEM" MODIFIED_WHEN="2014-11-05 10:37:08.0"/>
  <ROLES ID="12" ROLE_ID="ANDS-Curated" ROLE_TYPE_ID="ROLE_ORGANISATIONAL" NAME="Australian National Data Service Curated" AUTHENTICATION_SERVICE_ID="AUTHENTICATION_BUILT_IN" ENABLED="1" CREATED_WHEN="2014-11-05 10:33:01.0" CREATED_WHO="u1" MODIFIED_WHO="SYSTEM" MODIFIED_WHEN="2014-11-05 10:33:01.0"/>

</dataset>
