=== au-research/ANDS-ResearchVocabularies-Registry/src/test/resources/deploy/test/dbunit-toolkit-export-choice.dtd
<!ELEMENT dataset (
   (ACCESS_POINTS|
    LOG|
    RELATED|
    TASK|
    TODO|
    VERSIONS|
    VOCABULARIES)*)>

<!ELEMENT ACCESS_POINTS EMPTY>
<!ATTLIST ACCESS_POINTS
    ID CDATA #IMPLIED
    PORTAL_DATA CDATA #IMPLIED
    TOOLKIT_DATA CDATA #IMPLIED
    TYPE CDATA #IMPLIED
    VERSION_ID CDATA #IMPLIED
>

<!ELEMENT LOG EMPTY>
<!ATTLIST LOG
    ID CDATA #IMPLIED
    CLASS CDATA #IMPLIED
    MESSAGE CDATA #IMPLIED
    TYPE CDATA #IMPLIED
>

<!ELEMENT RELATED EMPTY>
<!ATTLIST RELATED
    ID CDATA #IMPLIED
    DATA CDATA #IMPLIED
    RELATION CDATA #IMPLIED
    SLUG CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    TYPE CDATA #IMPLIED
>

<!ELEMENT TASK EMPTY>
<!ATTLIST TASK
    ID CDATA #IMPLIED
    PARAMS CDATA #IMPLIED
    RESPONSE CDATA #IMPLIED
    STATUS CDATA #IMPLIED
    VERSION_ID CDATA #IMPLIED
    VOCABULARY_ID CDATA #IMPLIED
>

<!ELEMENT TODO EMPTY>
<!ATTLIST TODO
    ID CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    SUMMARY CDATA #IMPLIED
>

<!ELEMENT VERSIONS EMPTY>
<!ATTLIST VERSIONS
    ID CDATA #IMPLIED
    DATA CDATA #IMPLIED
    STATUS CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    VOCAB_ID CDATA #IMPLIED
>

<!ELEMENT VOCABULARIES EMPTY>
<!ATTLIST VOCABULARIES
    ID CDATA #IMPLIED
    CREATED_DATE CDATA #IMPLIED
    DATA CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    LICENCE CDATA #IMPLIED
    MODIFIED_DATE CDATA #IMPLIED
    MODIFIED_WHO CDATA #IMPLIED
    OWNER CDATA #IMPLIED
    POOL_PARTY_ID CDATA #IMPLIED
    SLUG CDATA #IMPLIED
    STATUS CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    USER_OWNER CDATA #IMPLIED
>

=== au-research/ANDS-ResearchVocabularies-Registry/src/test/resources/deploy/test/tests/TransformProviderTests.testJsonTreeTransformProvider1/input-toolkit-dbunit.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "../../dbunit-toolkit-export-choice.dtd" >
<dataset>
  <VOCABULARIES
      ID="1"
      OWNER="ands"
      TITLE="testJsonTreeTransformProvider1"
      SLUG="testjsontreetransformprovider1"
      />
  <VERSIONS
      ID="1"
      VOCAB_ID="1"
      TITLE="v1" />
  <ACCESS_POINTS/>
  <TASK
      ID="1"
      VOCABULARY_ID="1"
      VERSION_ID="1"
      PARAMS="[
                {
                  ''type'': ''HARVEST'',
                  ''provider_type'': ''File'',
                  ''file_path'': ''{CLASSES}/test/tests/ToolkitTests.testJsonTreeTransformProvider1/test-data1.ttl''
                },
                {
                  ''type'': ''TRANSFORM'',
                  ''provider_type'': ''JsonTree''
                }
              ]"
      />
  <TASK
      ID="2"
      VOCABULARY_ID="1"
      VERSION_ID="1"
      PARAMS="[
                {
                  ''type'': ''UNHARVEST'',
                  ''provider_type'': ''File''
                },
                {
                  ''type'': ''HARVEST'',
                  ''provider_type'': ''File'',
                  ''file_path'': ''{CLASSES}/test/tests/ToolkitTests.testJsonTreeTransformProvider1/test-data2.ttl''
                },
                {
                  ''type'': ''TRANSFORM'',
                  ''provider_type'': ''JsonTree''
                }
              ]"
      />
  <TASK
      ID="3"
      VOCABULARY_ID="1"
      VERSION_ID="1"
      PARAMS="[
                {
                  ''type'': ''UNHARVEST'',
                  ''provider_type'': ''File''
                },
                {
                  ''type'': ''HARVEST'',
                  ''provider_type'': ''File'',
                  ''file_path'': ''{CLASSES}/test/tests/ToolkitTests.testJsonTreeTransformProvider1/test-data3.ttl''
                },
                {
                  ''type'': ''TRANSFORM'',
                  ''provider_type'': ''JsonTree''
                }
              ]"
      />
  <TASK
      ID="4"
      VOCABULARY_ID="1"
      VERSION_ID="1"
      PARAMS="[
                {
                  ''type'': ''UNHARVEST'',
                  ''provider_type'': ''File''
                },
                {
                  ''type'': ''HARVEST'',
                  ''provider_type'': ''File'',
                  ''file_path'': ''{CLASSES}/test/tests/ToolkitTests.testJsonTreeTransformProvider1/test-data4.ttl''
                },
                {
                  ''type'': ''TRANSFORM'',
                  ''provider_type'': ''JsonTree''
                }
              ]"
      />
  <TASK
      ID="5"
      VOCABULARY_ID="1"
      VERSION_ID="1"
      PARAMS="[
                {
                  ''type'': ''UNHARVEST'',
                  ''provider_type'': ''File''
                },
                {
                  ''type'': ''HARVEST'',
                  ''provider_type'': ''File'',
                  ''file_path'': ''{CLASSES}/test/tests/ToolkitTests.testJsonTreeTransformProvider1/test-data5.ttl''
                },
                {
                  ''type'': ''TRANSFORM'',
                  ''provider_type'': ''JsonTree''
                }
              ]"
      />
</dataset>
